모임 기능 1차 프로토타입 개발
Network-office/Network-office-BE pull request #15
Opened 2024-09-20 17:42 UTC by sss4920

## 구현 내용

> 모임 구현에 대한 1차 프로토타입입니다.

## 목차

- 엔티티 구성.
- 간단한 기능별 플로우 설명.
- 아직 하지못한 TODO들.

## 엔티티 구성입니다.
Applicants - `모임 신청`. User와 Gathering의 중간 엔티티입니다.
Gathering - `모임`
GatheringUserConfirmManager - User와 Gathering의 `확정된 인원을 관리하는 중간 엔티티`입니다.
DeletedGathering - `삭제된 모임` 테이블입니다.
DeletedGatheringManager - `삭제된 모임과 유저, 삭제되기 전 원래의 모임 id가 존재하는 중간 엔티티`입니다.
BlockedUser - `차단된 유저`입니다.

GatheringAuthority - `모임 유저의 권한을 나타내는 enum`입니다. HOST, CONFIRMED가 존재합니다.
Category - 카테고리를 나타내는 enum입니다.

PlaceInfo - `모임의 장소정보` 임베디드 테이블입니다.
TimeInfo  - `모임의 시간정보` 임베디드 테이블입니다.

> 현재 수정 중인 부분으로 프론트의 mock에서 빠뜨린 필드로 인하여 Gathering 필드를 수정하고 있고, 
삭제된 모임의 종류가 생각해보니 성공적으로 마무리 되었을 때(리뷰와 별점), 파토났을 때(파토사유), 신고당했을 때(신고사유)와 같이 분류가 되어있어서 추상화를 고민하고 있습니다.

## 프로토타입 ERD
> (현재 모임부분에 대해서만 ERD를 작성했고, 현재 개발초기이므로 편의상 java 타입으로 작성해뒀습니다.)
![image](https://github.com/user-attachments/assets/6dbd2eef-d39a-4bfa-8859-4839703ccae3)

## 간단한 기능별 플로우 설명
1. 모임 신청 도메인
- 모임 신청 생성: 모임신청 객체를 생성한다.
- 모임 신청 조회: 요청을 보낸 유저가 호스트인지 확인하고, 호스트인 경우 해당하는 모임과 연결된 모임신청 객체를 모두 조회할 수 있습니다.
- 모임 신청 거절: 요청을 보낸 유저가 호스트인지 확인하고, 해당 모임 신청 객체를 삭제할 수 있습니다.
- 모임 신청 수락: 요청을 보낸 유저가 호스트인지 확인하고, 확정된 인원 매니저를 통해 확정된 인원으로 추가합니다. 그리고 해당 신청 객체를 삭제합니다.

2. 모임 도메인
- 모임 생성: 지도 마커에 필요한 데이터 및 dto등을 받아 모임을 생성합니다. 이 때 요청을 보낸 유저는 GatheringUserConfirmManager 객체를 생성해 HOST 권한을 갖게됩니다.
- 모임 상세 조회: 현재 삭제된 모임 아이디인지 조회해보고 아니라면, 해당 모임에 대한 상세정보를 주는 api입니다.(현재 수정중)
- 모임 정보 시/동/구 조회: dto를 받으면 해당 필드들을 보고 그 지역에 해당하는 모임을 response로 던져주는 api입니다. 
  - 현재 생각하는 플로우는 2가지입니다.
    -  해당 지역을 기반으로 km단위등도 수집해서 원을 그리고 해당하는 모임을 가져온다. 
    -  (위 방법은 redis에 존재하는 Geospatial등을 사용하여 구현하는 걸 생각하고 있습니다.)
    - 시/동/구 단위로 일치하는 부분에 있어서 가져온다. 
    - 1차 볼륨에서는 위 방법이 적절할 것 같습니다.
- 모임 수정 : 삭제되었는지 여부를 판단해야할까? 부분은 클라와 상의를 해봐야할 것 같습니다. 
  - dto를 통해 필요한 필드를 수정받습니다. 
  - 아마 전체 폼을 보여주고 수정할 것 같아서 PUT 요청을 생각하고 있습니다.
- 모임 삭제 : 
  - 모임이 이미 삭제되었는지 확인.
  - 삭제하려는 유저가 호스트인지 확인.
  - 파토사유등을 작성하여 삭제된 모임 객체를 생성
  - 삭제된 모임 매니저객체를 원래 모임 Id, 호스트, 기존 모임id를 등록하여 생성합니다.
  - 마지막으로 모임을 삭제합니다.

(그 외에 나머지 서비스들은 최대한 도메인로직의 결합을 분리해보려고 만든 서비스들입니다.)

## 아직 처리중인 TODO들
현재 다음과 같은 TODO들을 처리, 고민하고 있습니다.
1. 현재 확정된 인원 객체를 생성했을 때, 양방향 연관관계 설정에서 모임쪽에 넣어주는 로직을 처리 및 수정 하고 있습니다.
2. 차단된 유저를 중간 엔티티로 관리하는 것이 좋을지등을 고민하고 있습니다.(현재 생각은 정보가 필요한 것이 아닌 오로지 해당 user를 모임으로 부터 격리시키고 격리 사유만 보여주는 것이 맞다고 생각하여 엮지 않을 것 같습니다.)
3. 카테고리 유형으로 어떤 것들을 넣을지 고민중입니다.
4. 성공적으로 종료했을 때, 채팅방도 같이 지울 것인지, 채팅방은 남겨둘 것인지에 따라서 채팅 도메인을 연관지어 erd를 수정해봐야할 것 같습니다.

2024-09-21 19:28 UTC, YehyeokBang requested changes
많은 기능들이 포함되어 있어 힘드셨을텐데 1차 프로토타입 만드시느라 고생하셨습니다! 우선 연관관계 매핑, 메서드 분리, 명확한 이름, 포맷팅을 집중적으로 리뷰 남겼습니다!

## 이후 작업 요청 사항
- 불필요한 import 문 제거
- 포맷팅 이후 제출 (공백 등)

맞춰주시면 피드백하기 편하고 더 나은 코드를 만들어나갈 수 있을 것 같습니다!

## 객체 생성 패턴

빌더 패턴이 주를 이루지만 가끔 정적 팩토리 메서드 패턴도 보이는 것 같아요! 리뷰에도 남겨드렸지만, 여러 명이 참여하는 초기 개발 단계에서는 빌더 패턴이 더 나은 방법인 것 같습니다! (필드 개수도 많아지고, 필드 추가 및 제거 작업이 수시로 발생하기 때문) 우선 한가지로 정해서 작업 이후 의미를 부여하도록 변경하거나 그대로 가거나를 선택하면 좋을 것 같습니다!

## 연관관계 매핑

가끔 엔티티에 userId, gatheringId 등 값으로 엔티티의 PK를 가지는 경우가 있는 것 같습니다. 이는 충분히 연관관계 매핑을 통해 객체지향스럽게 문제를 해결할 수 있을 것 같습니다. 저도 한번 같이 고민해보겠습니다!

### DeleteGathering에 대한 의견

삭제(탈퇴, 터짐 등)된 모임을 따로 관리하나? 라는 느낌이 드는 것 같습니다. 아무래도 사유와 타입을 지정하기 위해 분리하신 것 같아요. 

그렇다면, 이름을 따로 사유 모음 의미를 나타낼 수 있는 이름으로 변경하고, Gathering이 상태(정상, 삭제 등)를 가지게 하는 것이 더 객체지향적인 것 같은데 어떻게 생각하시나요?

추가로 FetchType에 대해 고민해보시면 좋을 것 같아요.

## TODO 의견

> 1. 현재 확정된 인원 객체를 생성했을 때, 양방향 연관관계 설정에서 모임쪽에 넣어주는 로직을 처리 및 수정 하고 있습니다.
- 더 좋은 방향인 것 같습니다! 

> 2. 차단된 유저를 중간 엔티티로 관리하는 것이 좋을지등을 고민하고 있습니다.(현재 생각은 정보가 필요한 것이 아닌 오로지 해당 user를 모임으로 부터 격리시키고 격리 사유만 보여주는 것이 맞다고 생각하여 엮지 않을 것 같습니다.)
- DeleteGethering 의견이 도움이 될 것 같습니다.

> 3. 카테고리 유형으로 어떤 것들을 넣을지 고민중입니다.
- 다음 정기회의에서 논의해보면 좋을 것 같아요.

> 4. 성공적으로 종료했을 때, 채팅방도 같이 지울 것인지, 채팅방은 남겨둘 것인지에 따라서 채팅 도메인을 연관지어 erd를 수정해봐야할 것 같습니다.
- 채팅의 구조가 아직 명확하지 않아서 향후 다시 논의하면 좋을 것 같습니다.
- 저는 우선 모든 데이터를 남겨두는 것이 좋지 않을까? 라는 입장입니다!

## 기타

처음에는 Meeting이 더욱 직관적이지 않나라고 생각했지만, 저희가 만들려는 서비스 특성상 우리의 모임은 Gathering이 더 어울리는 것 같습니다! 좋아요. (프론트엔드 팀과 명칭을 통합하는 것도 좋을 것 같아요.)

> Gathering - 비즈니스적이거나 공식적인 느낌보다는 친근하고 자유로운 느낌이며, 다양한 형태의 모임(소셜 이벤트, 커뮤니티 모임, 취미 모임 등)에 적합하다고 해요.

객체지향적으로 고민해보기: 모임 스스로 할 수 있는 일은 모임이 책임을 가지게 만들고 하나씩 분리하다 보면 더 나은 구조를 가질 수 있을 것 같습니다. 저도 한번 고민해보겠습니다!

고생하셨습니다!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Applicants.java
> +}
```suggestion
/**
 * 신청 테이블을 따로 작성한다.
 * 신청을 넣는다 ->  신청 엔티티를 생성한다.
 * 신청을 수락한다. -> 신청 엔티티를 제거하고 모임유저에 추가.
 * 신청을 거절한다. -> 신청 엔티티를 제거한다.
 */
@Entity
@Getter
@Table(name = "applicants")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Applicants {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gathering_id")
	private Gathering gathering;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	private User user;

	@Builder
	private Applicants(Long id, Gathering gathering, User user) {
		this.id = id;
		this.gathering = gathering;
		this.user = user;
	}
}
```

## Fetch Type

<img width="381" alt="image" src="https://github.com/user-attachments/assets/539f80ba-c3b0-4e76-8111-21355758b0a1">

`@ManyToOne` 어노테이션의 default fetch type은 `Eager`로 설정되어 있습니다. N+1 문제와 같이 개발자가 예상할 수 없는 쿼리가 발생할 수 있기 때문에, 이러한 문제를 방지하기 위해 우선적으로 `Lazy` 타입으로 선언하는 것이 좋을 것 같아요!

`Lazy` 타입으로 지정한 경우 엔티티를 조회할 때 연관된 엔티티를 가져오지 않아 연관된 엔티티를 사용할 때 추가 쿼리가 발생할 수 있어요. 하지만 이는 `Fetch Join`, `@EntityGraph`, `DTO Projection`, `Batch Fetching` 와 같은 키워드를 공부하면 해결할 수 있기 때문에. 모든 연관관계는 `Lazy`로 명시하는 것이 좋을 것 같아요!

## 엔티티 명

- `Applicants` 라는 이름이 과도하게 추상화된 이름으로 느껴지는 것 같습니다. 주석이나 설명이 없는 경우 어떤 신청을 의미하는지 이해하기 힘든 것 같아요. 그래서 `GatheringApplicants` 와 같이 명확한 엔티티 명을 작성하면 더 좋을 것 같습니다!

## Builder 패턴

우선 저는 정적 팩터리 메서드 패턴을 선호하는 편이에요. 하지만 관련 필드가 4~5개를 넘는 경우 또는 개발을 시작하는 단계에서는 오히려 빌더 패턴을 사용하는 것이 개발할 때 편한 것 같아서 좋은 것 같습니다! 

빌더 패턴은 새로운 필드가 추가 되거나 순서에 민감하지 않기 때문에 개발 초기 단계에서 먼저 사용하고 추후 생성자에 이름을 넣으며 명확히 만드는 것도 좋은 방향인 것 같습니다! (빌더 패턴 vs 생성자의 성능 차이도 한번 같이 고민해보면 좋을 것 같아요!)

## 기타

일관성을 위해 클래스명과 첫 번째 필드 사이에 공백 한줄을 추가해주시면 좋을 것 같아요!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringApplyService.java
> +	}
```suggestion
	@Transactional(readOnly = true)
	public List<Applicants> readApplicantsByGathering(Long hostId, Long gatheringId){
	    // ApplicantRepository에 메서드 추가 필요
	    return applicantRepository.findByIdAndGatheringHostId(applicantId, hostId)
				.orElseThrow(() -> new IllegalArgumentException("신청id로 찾음"));
	}
```

- Applicant 엔티티를 조회하고 내부 내용을 확인하는 로직 대신 한번의 쿼리로 조건에 맞는 엔티티를 반환하거나 예외를 처리하는 것은 어떨까요?
- 추가로 `RuntimeException` 보다는 `IllegalArgumentException`이 더 어울리는 것 같아요. 
(잘못된 id로 요청이 들어오는 경우는 예를 들어 동기화가 되지 않은 화면에서 요청을 전송하는 경우가 있을 것 같아요.)

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringApplyService.java
> +	}
```suggestion
	@Transactional
	public void applyGathering(Long applicantId, Long gatheringId){
             User user = getUserById(applicantId);
             Gathering gathering = getGatheringById(gatheringId);
		//기존 모임에 이미 user가 있는지 체크

		//신청 엔티티 생성
		Applicants applicants = Applicants.builder()
			.gathering(gathering)
			.user(user)
			.build();
		applicantRepository.save(applicants);
	}
	
	// ...
	
	private User getUserById(Long applicantId) {
		return userRepository.findById(applicantId)
				.orElseThrow(()-> new IllegalArgumentException("유저없음"));
	}

	private Gathering getGatheringById(Long gatheringId) {
		return gatheringRepository.findById(gatheringId)
				.orElseThrow(()-> new IllegalArgumentException("모임 없음"));
	}
```

- 사용자를 찾아오는 로직처럼 자주 사용되는 로직이라면 메서드 분리를 통해 가독성과 재사용성을 높이는 것은 어떨까요?
- 추가로 일단 분리했지만, `applicantId` 로 사용자를 찾는 것이 맞는 건가요?

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/DeletedGatheringManagerService.java
> +}
포맷팅 이후 제출하시면 더 읽기 수월할 것 같습니다!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/TimeInfo.java
> +import java.sql.Time;
사용하지 않는 import 문은 제거하는 것이 좋을 것 같습니다!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/TimeInfo.java
> +	private String endTime;
`@DateTimeFormat` 어노테이션에 대해 간단하게 설명해주실 수 있을까요??

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/BlockedUser.java
> +	}
매개변수인 reason이 null이거나 빈 문자열인 경우를 검증할 수 있는 로직이 있으면 좋을 것 같습니다!

추가로 사유를 enum으로 관리하여 사용자가 선택하게 하는 것도 좋을 것 같습니다! 이 부분은 팀원들과 함께 논의해보면 좋을 것 같아요!

사유 선택 예시는 아래와 같습니다! (왜 block이 되었는지를 함께 생각해보면 좋을 것 같아요!)
<img width="437" alt="image" src="https://github.com/user-attachments/assets/f26dfe7e-fed7-49fa-a9cc-b4695ce59840">

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/BlockedUser.java
> +	private String reason;
JPA를 사용하고 있으니, 단순히 `userId`, `gatheringId` 같은 필드 대신 `연관관계 매핑`을 통해 문제를 해결하는 것이 좋을 것 같아요! `userId`와 `gatheringId`는 각각 `User 엔티티`와 `Gathering 엔티티`와 연관관계를 가질 수 있기 때문에, `객체지향적`으로 엔티티 간의 관계를 명확하게 표현하는 것이 더 좋은 코드가 될 것 같아요. 저도 한번 고민해보겠습니다!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +	}
호스트 검증 여부가 없는 로직인가요? 보이지 않아서 여쭤봅니다!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +		);
```suggestion
        DeletedGathering deletedGathering = deletedGatheringRepository.save(
                DeletedGathering.builder()
                        .reason(reason)
                        .deletedType(deletedType)
                        .build());
        DeletedGatheringManager gatherings = deletedGatheringManagerService.savingDeletedGathering(
                confirmManager.getUser(),
                deletedGathering
        );
```

\* 빌더 패턴 포맷팅

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/domain/GatheringAuthority.java
> +}
```java
public enum GatheringRole {
    HOST,               // 모임의 주인
    CONFIRMED_MEMBER    // 수락된 멤버
}
```

- 더 명확한 이름으로 제안드립니다!
- (OWNER, PARTICIPANT), (HOST, MEMBER), (ORGANIZER, CONFIRMED_MEMBER) 등 다양한 조합이 있을 것 같은데 어떤 것이 더 좋을 것 같은지 의논해봐요!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/DeletedGatheringManager.java
> +	private Long originGatheringId;
\* 연관관계 매핑 고려

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +	private final DeletedGatheringManagerRepository deletedGatheringManagerRepository;
```suggestion
@Service
@RequiredArgsConstructor
public class GatheringService {

	private final GatheringRepository gatheringRepository;
	private final UserRepository userRepository;
	private final GatheringAuthorityManagerService gatheringAuthorityManagerService;
	private final DeletedGatheringManagerService deletedGatheringManagerService;
	private final GatheringManagerRepository gatheringManagerRepository;
	private final DeletedGatheringRepository deletedGatheringRepository;
	private final DeletedGatheringManagerRepository deletedGatheringManagerRepository;
```
\* 공백 추가

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringApplyService.java
> +		}
조건문에 부정문 대신 긍정문을 넣는 방법이 더 좋을 것 같아요! [참고 블로그](https://kghworks.tistory.com/66)

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/GatheringUserConfirmManager.java
> +	private User user;
\* fetch type Lazy 지정 및 `@JoinColumn`

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +	private Long hostId; //모임대표는 프로필을 볼수 있어야한다. 필요한 타입으로 임베디드로 바꿔야할지도
연관관계 매핑으로 이 문제를 해결할 수 있을 것 같아요!

2024-09-21 19:28 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/domain/Category.java
> +}
다음 정기 회의에서 카테고리를 정해보면 좋을 것 같아요!

2024-09-22 08:30 UTC, sss4920 commented
## 적극적인 리뷰에 대한 감사

> 오 급하게 만들다보니 빠뜨린 내용들이 많네요.. 일단 격하게 공감하는 부분들을 처리하고 추가 커밋을 제출해보도록 하겠습니다!

2024-09-23 06:08 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringApplyService.java
> +	}
좋은 생각입니다! 수정해보겠습니다.☺️

2024-09-23 06:21 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringApplyService.java
> +	}
좋은 생각입니다!
> 추가로 일단 분리했지만, applicantId 로 사용자를 찾는 것이 맞는 건가요?
아닙니다, 유저Id로 찾아야하는데, 이곳저곳 한번에 바꾸다보니 섞여 들어간 것 같네요; 참고해서 수정해보겠습니다! 꼼꼼한 리뷰 덕분에 발견할 수 있었네요!☺️

2024-09-23 06:39 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/TimeInfo.java
> +	private String endTime;
시간 형태를 지정해서 넣을까해서 적어놨다가 지우지 않았었네요; 
```
@DateTimeFormat(pattern = "yyyy-MM-dd")
private Date startDate;
```
다음과 같이 날짜형식을 지정해서 컬럼을 만들려고 했었는데, 패턴에 대해 협의한 내용이 없어서 나중에 클라와 얘기해서 설정해볼까합니다..!  현재는 그냥 날리겠습니다.

2024-09-23 07:01 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/BlockedUser.java
> +	}
사유 선택이 조금 더 적절하겠네요. 차단된 이유에 대해서 디테일하게 설명하는 것보다는 enum으로 처리하는 것이 더 좋을 것 같습니다. 이 부분은 다음 회의에서 같이 의견을 나누면 좋을 것 같네요!

2024-09-23 08:13 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/BlockedUser.java
> +	private String reason;
그렇군요..! 제 생각에도 중간 엔티티 개념으로 빼는 것이 더 관리하기 좋아보이네요! 덕분에 엔티티 설계에 근거가 생겨 더 좋은 코드를 작성할 수 있을 것 같습니다!☺️

포맷팅과 함께 수정을 거쳐보겠습니다!

2024-09-24 04:47 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +	}
호스트 검증여부가 빠졌군요! 수정하겠습니다!

2024-09-24 04:51 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/domain/GatheringAuthority.java
> +}
그렇군요! 확실히 저도 어떤 명확한 이름으로 해야할지 좀 고민하던 참이었습니다.. 이부분은 이번 회의 때 한번 물어보고 수정을 거쳐보도록 하겠습니다!

2024-09-24 04:54 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/DeletedGatheringManager.java
> +	private Long originGatheringId;
## 질문
여기는 헷갈리는 것이 원래 모임을 삭제했을 때 기록하는 테이블인데 연관관계 매핑을 하는 것이 좋을지 잘 모르겠습니다!
> user는 위처럼 연관관계 매핑 처리를 제대로 해보겠습니다!

2024-09-24 04:58 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +	private Long hostId; //모임대표는 프로필을 볼수 있어야한다. 필요한 타입으로 임베디드로 바꿔야할지도
이 부분은 다시 생각해보니 확정된 인원에 이미 host에 대한 정보도 같이 들어있어서 hostId는 제거하는 것이 좋아보입니다!
대신에 Gathering안에서 host 정보를 바로 보여줄 수 있는 메서드를 만드는 방식으로 하면 더 좋아보입니다!

2024-09-24 05:01 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringApplyService.java
> +		}
오 확실히 가독성이 좋아지는 군요! 수정해보겠습니다!☺️

2024-09-24 05:02 UTC, djdongjae reviewed
# 리뷰
엄청 머리 아픈 부분이이었을텐데 그래도 누구도 손대지 못한 부분 먼저 시도해주셔서 감사합니다..🤗

## ERD 설계
코드의 세세한 부분은 같이 천천히 고쳐 나가면 될 것 같고, 저는 ERD 구조를 조금 더 단순화 시킬 수 있지 않을까 조심스럽게 제안해 봅니다.
* 먼저 `User`, `Applicants`, `Gathering`으로 이루어진 기본적인 구조는 동일합니다.
* 다만 관계형 데이터베이스 설계시 다른 테이블 간의 연산으로부터 유도 가능한 값은 따로 테이블로 설계하지 않습니다.
* 따라서 위 3개의 테이블 간의 연산으로부터 가능한 값들을 저장하는 `DeletedGatheringManager`, `GatheringUserConfirmManager`, `DeletedGathering`은 새로운 필드를 추가하거나 관계대수를 통해 처리할 수 있지 않을까 합니다.

## 제안

<img width="735" alt="Screenshot 2024-09-24 at 1 47 47 PM" src="https://github.com/user-attachments/assets/82ba4233-63ef-4b12-802f-ad5d2123e42a">

<br>

* 간략한 ERD는 이런식으로 생각해 보았습니다. 
* 물론 틀렸을 수도 있으니 다시 얘기해 보아요!

2024-09-24 05:02 UTC, djdongjae commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/dto/request/GatheringDto.java
> +	String gu,
시, 동, 구로 나뉘어지는 행정 구역이 많긴하지만, 군 같은 경우에는 읍, 면, 동으로 구분되기도 하기 때문에 필드를 나누기 보다 하나의 String 값으로 받는 것은 어떨까요?

2024-09-24 05:02 UTC, djdongjae commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/domain/DeletedType.java
> +	PATO,
PATO 보다 CANCELED는 어떨까요?

2024-09-24 05:10 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/dto/request/GatheringDto.java
> +	String gu,
이 부분은 클라이언트쪽과도 상의를 해본 결과 전체 주소와 저런식으로 나눠서 주고 있어서 다시한번 얘기 해보고 수정을 거쳐보겠습니다!

2024-09-24 05:12 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/domain/DeletedType.java
> +	PATO,
좋은 단어가 생각안났는데..ㅎ 더 명확한 단어인 것 같습니다!☺️ 수정하겠습니다!

2024-09-25 15:47 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/domain/Category.java
> +}
금일 회의를 통해 결정되었으니 해당 내용 수정해보겠습니다!

2024-10-07 04:00 UTC, YehyeokBang requested changes
## 중간 리뷰

고생하셨습니다! 궁금한 부분이나 개선하면 좋을 부분에 대해 중간 리뷰를 작성했습니다!

## 추가 내용

- `@XXXMapping()` 어노테이션에 작성하는 URI 문자열을 "/api/v1/..." 형태 대신 "api/v1/..." 형태로 통일하는 것이 좋을 것 같습니다! 예시: "/deny" -> "deny", "/gatheringId" -> "gatheringId"
- 가끔 depth가 깊어지거나 하나의 메서드에서 많은 역할을 수행하는 경우가 있는 것 같습니다. 메서드 분리를 통해 이를 해결하는 것은 어떨까요?
- 주석 및 공백 통일성, 조금 더 지켜주시면 가독성에 도움이 될 것 같아요!

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    private GatheringStatus status;
```java
@Enumerated(EnumType.STRING)
private GatheringStatus gatheringStatus;

@Enumerated(EnumType.STRING)
private GatheringStatus status;
```

두 필드의 차이는 무엇인가요?

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    }
DTO에 대한 의존이 생기는 것 같아요. 메서드를 분리하거나 값으로 받는다면 DTO가 없어도 될 것 같습니다!

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    }
```suggestion
    public List<User> getConfiremedUserList() {
        return gatheringUserList.stream()
                .filter(this::isConfirmedUser)
                .map(GatheringUser::getUser)
                .toList();
    }

    // 예시 메서드 분리
    private boolean isConfirmedUser(GatheringUser gatheringUser) {
        return gatheringUser.getGatheringUserStatus()
                .equals(GatheringUserStatus.CONFIRMED_USER);
    }
```

필터 부분에서 메서드 분리를 통해 명확하게 표현하면 좋을 것 같습니다!

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
만약 builder로 만들어지는 Gathering이 모두 처음 생성되는 모임이라면, status(IN_PROGRESS)는 `@Builder.Default`를 사용하여 디폴트 값으로 만들어두는 것은 어떨까요?? 

이렇게 하면 해당 필드를 명시적으로 설정하지 않더라도 기본값이 적용되므로 휴먼 에러를 줄일 수 있을 것 같습니다!

```java
// 예시
@Builder.Default
private GatheringStatus status = GatheringStatus.IN_PROGRESS;
```

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
해당 메서드에서 user 객체를 사용하지 않는 것 같아요. 확인 부탁드려요!

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/GatheringController.java
> +    }
userId를 파라미터로 받는 것 대신 Security Context에 존재하는 인증 정보를 사용하면 좋을 것 같습니다! 
Principal 객체의 getName() 메서드를 사용하면 저장된 세션에서 userId를 가져올 수 있습니다.

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
객체지향 생활체조 원칙 중 하나인 [한 줄에 점 하나만 찍는다](https://limdingdong.tistory.com/10)를 읽어보면 도움이 될 것 같습니다!

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gatheringUser/domain/GatheringUser.java
> +    private User user;
연관관계 매핑으로 문제를 해결한 점 좋아요!

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gatheringUser/domain/GatheringUser.java
> +    }
만약 매개변수로 받는 문자열 객체가 null인 경우는 어떻게 될까요?

2024-10-07 04:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
추가로 하나의 메서드가 꽤 많은 역할을 수행하고 있는 것 같습니다! 적절하게 분리하면 더욱 명확한 코드가 될 것 같아요

2024-10-07 06:31 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    private GatheringStatus status;
헉 밑에 status로 변경되었는데 지우지 못한 필드였네요.. 수정하겠습니다!

2024-10-07 06:38 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    }
그런 문제가 발생하는군요! 꼼꼼한 리뷰 감사합니다!

2024-10-07 06:39 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    }
더 깔끔하게 표현하고 싶었는데 이런식으로 스트림을 처리할 수 있네요! 많이 배웁니다!! ☺️

2024-10-07 06:45 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
인증이 필요한 유저인지를 확인하려다 보니 조회를 한번 넣었던 것 같습니다. 
생각해보니 이미 인증한 유저이니 검증이 필요없겠군요! 제거하겠습니다!

2024-10-07 06:46 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/GatheringController.java
> +    }
그렇군요! 모두들 수정해보겠습니다!

2024-10-07 06:50 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
오 .을 찍을수록 결합도를 나타낸다라 설득력있고 좋은 글인 것 같습니다! 고려해서 코드를 수정해보겠습니다!

2024-10-07 06:58 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/service/GatheringService.java
> +    }
확실히 위와 같은 휴먼에러가 많은 것으로 봐서; 너무 설득력있는 의견입니다! 반영하겠습니다!!💦☺️

2024-10-07 11:45 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/dto/request/GatheringDto.java
> +	String gu,
상의 해본 결과 시,동,구로 그냥 나눠서 준다고 합니당..!☺️

2024-10-07 11:46 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gatheringUser/domain/GatheringUser.java
> +    }
그렇군요! 이런 경우에는 간단히 Assert.NotNull등을 고려해보면 될 것 같습니다! 다른 부분에도 참고하여 추가해보겠습니다!

2024-10-08 15:16 UTC, YehyeokBang commented
## 대면 코드 리뷰

> 대면으로 진행한 코드 리뷰 내용을 반영했습니다. 아래 내용을 참고하여 진행 부탁드립니다!

## 확인 필요
- 전반적으로 호스트 검증이 필요합니다.
- 테스트 결과 특정 모임을 성공적으로 완료했다가 다시 취소하거나 반대로도 가능합니다.
- 자신이 만든 모임에 직접 가입 신청을 할 수 있습니다.
- 모임 신청 수락 API가 정상적으로 작동하지 않습니다.
- develop에 머지된 휴대폰 인증 부분이 적용되지 않았습니다. 리뷰 반영 후 develop 브랜치 pull을 진행하고 테스트하면 좋을 것 같습니다!

## 질문 내용

- 특정 필드를 변경하려고 할 때 PUT 메서드와 PATCH 메서드 모두 사용하신 것 같습니다. 둘의 차이점은 무엇이 있을까요?
- URL에 동사가 들어가는 경우가 많은 것 같습니다. 이는 좋은 설계일까요? URL와 관련된 의견을 듣고 싶습니다!

2024-10-08 15:18 UTC, YehyeokBang requested changes
## 기타 

- 요청을 위해 사용하는 dto에 JSON 형식을 지정하면 더 좋을 것 같습니다! (요청 일관성을 위해)
예시: `@JsonProperty("phone_number")`
- 추가로 궁금한 점은 편하게 말씀해주세요!

2024-10-09 15:04 UTC, sss4920 commented
## 대면 코드 리뷰에 대한 감사

너무 유익한 시간이었던 것 같습니다. 대체적으로 중복되는 코드들을 처리하는 방법들과 객체들에게 메시지를 부여하는 것에 대해서 큰 깨달음을 얻었던 것 같습니다!
 
> * 전반적으로 호스트 검증이 필요합니다. 

조인등을 고려하여 호스트를 검증하는 과정을 더 고민해보겠습니다!

> * 테스트 결과 특정 모임을 성공적으로 완료했다가 다시 취소하거나 반대로도 가능합니다. 

성공적으로 완료된 경우에 대해서 취소하려고 한다든지에 대한 엣지 케이스들을 validation하는 것들을 추가해봐야겠군요!
> * 자신이 만든 모임에 직접 가입 신청을 할 수 있습니다. 

신청을 넣는 부분에서 이미 호스트인지를 검증하는 validation을 고려해보겠습니다!

> * 모임 신청 수락 API가 정상적으로 작동하지 않습니다.

이 부분은 어디가 원인일지 바로 생각나지않아 확인해보고 추가해보겠습니다!
> * develop에 머지된 휴대폰 인증 부분이 적용되지 않았습니다. 리뷰 반영 후 develop 브랜치 pull을 진행하고 테스트하면 좋을 것 같습니다!

네! 진행해보겠습니다!


> ## 질문 내용
> * 특정 필드를 변경하려고 할 때 PUT 메서드와 PATCH 메서드 모두 사용하신 것 같습니다. 둘의 차이점은 무엇이 있을까요?

PATCH는 일부의 자원 필드만 바뀔 때, PUT은 해당 자원에 대한 전체적인 내용이 바뀌어 새로운 자원으로 대체되는 것으로 알고있습니다.
현재 모임을 수정할 때에는 해당 모임에 대한 전체적인 정보를 수정할 때의 입력 폼을 기반으로 새로운 정보로 완전 대체되는 플로우로 이해하고 있었기에 PUT을 사용했고, PATCH같은 경우 대부분 모임의 상태만을 변경할 때, 즉 전체적인 필드가 아니라 일부분만 변하는 API로 이해하였기 때문에 다음과 같이 작성했던 것 같습니다!
> * URL에 동사가 들어가는 경우가 많은 것 같습니다. 이는 좋은 설계일까요? URL와 관련된 의견을 듣고 싶습니다!

URL에 동사가 들어가면 REST하지 않다고 생각합니다. 자원의 위치와 요청 메소드를 통해서만 나타내야한다고 생각하고 있었는데, 좋은 방법이 마땅히 떠오르지 않았습니다.
지금 드는 생각은 PathParameter등으로 상태값을 받아서 비슷한 기능을 하는 컨트롤러들을 하나로 합치면 좋은 URL 설계가 되지않을까 생각하는데 어떻게 생각하시나요?

2024-10-10 14:54 UTC, YehyeokBang commented
> URL과 관련된 내용과 추가적인 코드 리뷰는 정리되면 답변하겠습니다!

## 기타
- build.gradle 파일에 conflict가 발생한 것 같습니다! 확인 부탁드려요!

2024-10-13 08:00 UTC, YehyeokBang approved these changes
많이 복잡하다면 복잡할 수 있는 기능 구현하시느라 고생하셨습니다! 수정이 필요한 간단한 부분은 직접 작업했습니다. 확인 부탁드려요!

## 머지 이후 진행할 작업

- 모임 id로 모임을 조회하는 기능과 위치와 id를 리스트로 조회하는 기능
현재는 시, 동, 구로 조회합니다. 이를 둘로 쪼개어 위치와 id, 간단한 정보들만 포함하여 리스트로 조회하는 기능으로 지도에 포인트를 찍게 하고 그 포인트를 누를 때 id로 조회하여 해당 모임의 자세한 내용을 조회할 수 있게 만들어야 할 것 같습니다.
- 현재 id 값만 바꾸면 누구나 다른 모임의 신청 대기 목록을 조회할 수 있습니다! 수정 필요.

나머지는 프론트 파트의 피드백이 필요할 것 같습니다. 고생하셨어요!

2024-10-13 08:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/GatheringController.java
> +    }
`@GetMapping` 처럼 `() 괄호` 안에 값이 없는 경우 깔끔함을 위해 괄호를 제거했습니다!

2024-10-13 08:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/controller/GatheringController.java
> +    }
두 작업 모두 특정 gathering에 대한 작업이기 때문에 `@PathVariable("gatheringId")`으로 gathering이라는 자원을 표시할 수 있도록 수정했습니다.

2024-10-13 08:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    }
별점과 모임 상태에 대한 검증 메서드를 추가했습니다.

이전에는 성공적으로 종료된 모임의 상태를 취소(파토)로 변경할 수 있었고 반대로도 가능했습니다.

2024-10-13 08:00 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/global/exception/handler/GlobalExceptionHandler.java
> +    }
예외를 핸들링 할 수 있게 추가했습니다!

2024-10-13 08:18 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/gathering/entity/Gathering.java
> +    }
아 진행중인 모임에만 변경할 수 있다는 validation을 추가하는 발상을 못했던 것 같습니다! 좋은 변경사항이네요☺️

2024-10-13 08:20 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/global/exception/handler/GlobalExceptionHandler.java
> +    }
좋은 것 같습니다..! 저도 추가하고자 하는 예외가 있다면 해당 핸들러에 추가 해보겠습니다!

2024-10-14 11:42 UTC, djdongjae approved these changes
수고하셨습니다!!

2024-10-14 12:25 UTC, merged