피드 기능 구현
Network-office/Network-office-BE pull request #23
Opened 2024-11-16 14:43 UTC by YehyeokBang

## 내용

피드, 댓글, 좋아요 기능을 구현합니다.

- 피드 작성 및 조회(목록, 단일)
- 댓글 작성 기능 (1depth)
- 좋아요 및 취소 기능
- 관련 테스트 코드 작성

> 임시로 구현한 부분이 많아서 사용해 보면서 수정이 필요합니다.

## 필요한 기능

- 조회수 기능 (현재는 LMS 처럼 조회하면 제한 없이 조회수가 늘어납니다.)
- 사용자 엔티티 추출 기능 (반복되는 코드를 줄일 필요가 있을 것 같습니다.)

2024-11-18 08:18 UTC, sss4920 requested changes
수고하셨습니다!! 최근에 프리코스 활동으로 엄청 바쁘셨던 것 같은데 테스트 코드까지 잘짜신 것 같네요..! 몇 가지 질문 사항을 적어봤습니다! ☺️

2024-11-18 08:18 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/feed/entity/Feed.java
> +    private Long view = 0L;
아예 null값을 false로 만든다면 그냥 long 타입을 사용하는 것은 어떤지 궁금합니다!

2024-11-18 08:18 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/feed/entity/Likes.java
> +    @JoinColumn(name = "feed_id")
좋아요에서 피드는 null인 경우가 있는 걸까용??

2024-11-18 08:18 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/feed/entity/Likes.java
> +    private static void validateArguments(User user, Feed feed) {
오 이런식으로 유효성 검사도 따로 빼주는거 보기 편한거같아요!☺️

2024-11-18 08:18 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/feed/service/CommentService.java
> +        checkAuthor(targetComment, author);
`checkAuthor`라는 함수는 댓글 안에서 저자가 맞는지 검사하는게 더 엔티티의 역할에 맞게 구현할 수 있지않을까하는 생각이 듭니다! 만약 그렇게 된다면 다음과 같이 적을 수 있을 것 같아요..!
```java
if(targetComment.checkAuthor()){
  commentRepository.delete(targetComment);
}
```

2024-11-18 08:18 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/feed/service/CommentService.java
> +    private boolean isAuthor(Comment targetComment, User author) {
isAuthor 역시 Comment안에서 해결해주면 서비스 로직이 조금 더 서비스에만 집중할 수 있게 될 것 같습니다!!

2024-11-18 08:18 UTC, sss4920 commented on Network-Office/src/test/java/dev/office/networkoffice/feed/entity/LikesTest.java
> +    @CsvSource({
오 카테고리쪽에서와 다르게 여기서는 `null`로 주신 이유가 있을까용??

2024-11-18 10:35 UTC, YehyeokBang commented on Network-Office/src/test/java/dev/office/networkoffice/feed/entity/LikesTest.java
> +    @CsvSource({
두 케이스 모두 포함시킨다면 더 좋을 것 같습니다! 후반에 따로 좋아요를 분리하는 작업을 진행하면서 놓친 것 같아요..

2024-11-18 10:35 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/feed/service/CommentService.java
> +        checkAuthor(targetComment, author);
좋은 방법인 것 같아요! 적용하겠습니다!

2024-11-18 10:35 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/feed/entity/Likes.java
> +    @JoinColumn(name = "feed_id")
피드가 삭제된 경우 어떻게 처리할지에 대해 고민하다가, 현재는 별도의 조건을 추가하지 않았습니다. 
허나 지금 생각해 보니 피드 삭제 시 좋아요를 자동으로 함께 삭제하도록 하는 것이 직관적일 것 같다는 생각이 드네요. JPA의 `cascade` 속성을 활용해보겠습니다! 👍

2024-11-18 11:10 UTC, YehyeokBang commented
- 저자 검증 기능을 엔티티 객체가 스스로 할 수 있도록 변경합니다.
- 논리적으로 null이 들어갈 수 없는 필드를 Wrapper 클래스에서 기본 타입으로 변경합니다.
- 좋아요 쿼리 개선 및 복합 인덱스를 설정합니다.
- 피드가 삭제된 경우 좋아요도 삭제될 수 있도록 cascade 설정을 추가합니다.
- 관련 테스트 코드를 추가합니다.

@sss4920 @djdongjae 리뷰 반영했습니다!

2024-11-18 11:25 UTC, sss4920 approved these changes
수고하셨습니다!☺️

2024-11-18 11:25 UTC, sss4920 commented on Network-Office/src/main/java/dev/office/networkoffice/feed/service/CommentService.java
> +        if (!targetComment.isCreatedBy(author)) {
오 읽기 너무 좋은 것 같습니다..!☺️

2024-11-19 03:58 UTC, djdongjae approved these changes
역시 메소드별로 책임을 분리해서 코드를 잘 짜시는 것 같습니다..! 고생하셨습니다 🤗

2024-11-19 03:58 UTC, djdongjae commented on Network-Office/src/main/java/dev/office/networkoffice/feed/entity/Comment.java
> +        return author.equals(targetAuthor);
`NullPointerException` 방지를 위해 targetAuthor가 null일 경우를 대비하는 것은 어떨까요?

2024-11-19 03:58 UTC, djdongjae commented on Network-Office/src/main/java/dev/office/networkoffice/feed/service/FeedService.java
> +        return feedRepository.findAllByOrderByCreatedTimeDesc(pageable)
`pageable` 객체도 null일 가능성이 있을 것 같습니다!

2024-11-19 08:11 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/feed/service/FeedService.java
> +        return feedRepository.findAllByOrderByCreatedTimeDesc(pageable)
Default 값을 지정하면 좋을 것 같네요 감사합니다!

2024-11-19 08:11 UTC, YehyeokBang commented on Network-Office/src/main/java/dev/office/networkoffice/feed/entity/Comment.java
> +        return author.equals(targetAuthor);
좋은 방법 같아요! 👍

2024-11-19 08:33 UTC, merged